DEBUG 2015-05-24 11:50:22,672: 	 Executing command: 'submit'
DEBUG 2015-05-24 11:50:22,673: 	 Could not find CRAB cache file /home/dirack/.crab3; creating a new one.
DEBUG 2015-05-24 11:50:22,732: 	 CredentialException
Message: voms-proxy-info command not found
	ModuleName : WMCore.Credential.Proxy
	MethodName : __init__
	ClassInstance : None
	FileName : /cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/WMCore/Credential/Proxy.py
	ClassName : None
	LineNumber : 152
	ErrorNr : 0

Traceback: 


ERROR 2015-05-24 11:50:22,732: 	 Problem with Grid environment: voms-proxy-info command not found 
ERROR 2015-05-24 11:50:22,732: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 139, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 124, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 284, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/CredentialInteractions.py", line 123, in createNewVomsProxySimple
    proxy = self.proxy()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/CredentialInteractions.py", line 73, in proxy
    raise EnvironmentException('Problem with Grid environment: %s ' % ex._message)
EnvironmentException: Problem with Grid environment: voms-proxy-info command not found 
DEBUG 2015-05-24 11:51:59,978: 	 Executing command: 'submit'
DEBUG 2015-05-24 11:51:59,979: 	 Found CRAB cache file /home/dirack/.crab3
DEBUG 2015-05-24 11:51:59,989: 	 Checking credentials
DEBUG 2015-05-24 11:51:59,990: 	 Found proxy file /tmp/x509up_u500
DEBUG 2015-05-24 11:51:59,990: 	 Getting proxy life time left
DEBUG 2015-05-24 11:52:01,496: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u500 -timeleft
 output : 42969

 error: 
 retcode : 0
DEBUG 2015-05-24 11:52:02,100: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u500 -actimeleft
 output : 42968

 error: 
 retcode : 0
DEBUG 2015-05-24 11:52:02,100: 	 Proxy valid for 11:56:09 hours
INFO 2015-05-24 11:52:02,101: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-05-24 11:52:02,101: 	 Loading CRAB configuration file.
DEBUG 2015-05-24 11:52:02,109: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR: OSError: [Errno 13] Permission denied: '/afs'

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: 3.3.16.patch1
Unhandled Exception!
[Errno 13] Permission denied: '/afs'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 139, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 124, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 294, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 333, in createWorkArea
    os.makedirs(workingArea)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/afs'
	Please use crab uploadlog to upload the log file /opt/CMMSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/crab.log
DEBUG 2015-05-24 11:56:09,757: 	 Executing command: 'submit'
DEBUG 2015-05-24 11:56:09,757: 	 Found CRAB cache file /home/dirack/.crab3
DEBUG 2015-05-24 11:56:09,766: 	 Checking credentials
DEBUG 2015-05-24 11:56:09,767: 	 Found proxy file /tmp/x509up_u500
DEBUG 2015-05-24 11:56:09,767: 	 Getting proxy life time left
DEBUG 2015-05-24 11:56:10,371: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u500 -timeleft
 output : 43187

 error: 
 retcode : 0
DEBUG 2015-05-24 11:56:10,975: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u500 -actimeleft
 output : 43186

 error: 
 retcode : 0
DEBUG 2015-05-24 11:56:10,976: 	 Proxy valid for 11:59:47 hours
INFO 2015-05-24 11:56:10,976: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-05-24 11:56:10,976: 	 Loading CRAB configuration file.
DEBUG 2015-05-24 11:56:10,978: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR: OSError: [Errno 13] Permission denied: '/afs'

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: 3.3.16.patch1
Unhandled Exception!
[Errno 13] Permission denied: '/afs'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 139, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 124, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 294, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 333, in createWorkArea
    os.makedirs(workingArea)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/external/python/2.6.8-comp6/lib/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/afs'
	Please use crab uploadlog to upload the log file /opt/CMMSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/crab.log
DEBUG 2015-06-01 23:51:55,462: 	 Executing command: 'submit'
DEBUG 2015-06-01 23:51:55,462: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-06-01 23:51:55,471: 	 Checking credentials
DEBUG 2015-06-01 23:51:55,471: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-06-01 23:51:55,471: 	 Getting proxy life time left
DEBUG 2015-06-01 23:51:56,079: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 85841

 error: 
 retcode : 0
DEBUG 2015-06-01 23:51:56,587: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 85840

 error: 
 retcode : 0
DEBUG 2015-06-01 23:51:56,587: 	 Proxy valid for 23:50:41 hours
INFO 2015-06-01 23:51:56,588: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-06-01 23:51:56,588: 	 Loading CRAB configuration file.
DEBUG 2015-06-01 23:51:56,589: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-06-01 23:51:56,589: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/CMSSW_7_2_3_patch1/src/m2n/maxi2ntuples/test/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-06-01 23:51:56,589: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 139, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 124, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 294, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 341, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/CMSSW_7_2_3_patch1/src/m2n/maxi2ntuples/test/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-06-01 23:54:25,806: 	 Executing command: 'submit'
DEBUG 2015-06-01 23:54:25,806: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-06-01 23:54:25,814: 	 Checking credentials
DEBUG 2015-06-01 23:54:25,814: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-06-01 23:54:25,814: 	 Getting proxy life time left
DEBUG 2015-06-01 23:54:26,318: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 85690

 error: 
 retcode : 0
DEBUG 2015-06-01 23:54:26,823: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 85690

 error: 
 retcode : 0
DEBUG 2015-06-01 23:54:26,824: 	 Proxy valid for 23:48:10 hours
INFO 2015-06-01 23:54:26,824: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-06-01 23:54:26,824: 	 Loading CRAB configuration file.
DEBUG 2015-06-01 23:54:26,838: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-06-01 23:54:26,838: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-06-01 23:54:26,838: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 139, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/bin/crab", line 124, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 294, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch1/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 341, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-06-09 11:01:20,640: 	 Executing command: 'submit'
DEBUG 2015-06-09 11:01:20,641: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-06-09 11:01:20,663: 	 Checking credentials
DEBUG 2015-06-09 11:01:20,664: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-06-09 11:01:20,664: 	 Getting proxy life time left
DEBUG 2015-06-09 11:01:24,180: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 83287

 error: 
 retcode : 0
DEBUG 2015-06-09 11:01:24,687: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 83287

 error: 
 retcode : 0
DEBUG 2015-06-09 11:01:24,687: 	 Proxy valid for 23:08:07 hours
INFO 2015-06-09 11:01:24,688: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-06-09 11:01:24,688: 	 Loading CRAB configuration file.
DEBUG 2015-06-09 11:01:24,692: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-06-09 11:01:24,694: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-06-09 11:01:24,694: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch2/bin/crab", line 139, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch2/bin/crab", line 124, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch2/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch2/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 294, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.16.patch2/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 341, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-07-03 22:29:10,267: 	 Executing command: 'status'
DEBUG 2015-07-03 22:29:10,269: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-07-03 22:29:10,298: 	 Checking credentials
DEBUG 2015-07-03 22:29:10,298: 	 Proxy file /tmp/x509up_u39587 not found
DEBUG 2015-07-03 22:29:10,298: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2015-07-03 22:29:16,224: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2015-07-03 22:29:16,730: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 86398

 error: 
 retcode : 0
DEBUG 2015-07-03 22:29:17,238: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 86397

 error: 
 retcode : 0
DEBUG 2015-07-03 22:29:17,745: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u39587 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2015-07-03 22:29:17,745: 	 Proxy created.
ERROR 2015-07-03 22:29:17,745: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/test
ERROR 2015-07-03 22:29:17,746: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1506-comp2/bin/crab", line 136, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1506-comp2/bin/crab", line 122, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1506-comp2/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 317, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1506-comp2/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 431, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1506-comp2/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 412, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N_For_Italians/src/m2n/maxi2ntuples/python/test
DEBUG 2015-08-04 01:21:42,573: 	 Executing command: 'submit'
DEBUG 2015-08-04 01:21:42,574: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-08-04 01:21:42,585: 	 Checking credentials
DEBUG 2015-08-04 01:21:42,585: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-08-04 01:21:42,586: 	 Getting proxy life time left
DEBUG 2015-08-04 01:21:43,090: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 84023

 error: 
 retcode : 0
DEBUG 2015-08-04 01:21:43,496: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 84023

 error: 
 retcode : 0
DEBUG 2015-08-04 01:21:43,496: 	 Proxy valid for 23:20:23 hours
INFO 2015-08-04 01:21:43,497: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-08-04 01:21:43,497: 	 Loading CRAB configuration file.
DEBUG 2015-08-04 01:21:43,501: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-04 01:21:43,502: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-08-04 01:21:43,502: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-08-14 10:33:43,907: 	 Executing command: 'submit'
DEBUG 2015-08-14 10:33:43,908: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-08-14 10:33:43,953: 	 Checking credentials
DEBUG 2015-08-14 10:33:43,953: 	 Proxy file /tmp/x509up_u39587 not found
DEBUG 2015-08-14 10:33:43,953: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2015-08-14 10:33:49,782: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2015-08-14 10:33:50,291: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 86398

 error: 
 retcode : 0
DEBUG 2015-08-14 10:33:50,797: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 86398

 error: 
 retcode : 0
DEBUG 2015-08-14 10:33:51,305: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u39587 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2015-08-14 10:33:51,306: 	 Proxy created.
INFO 2015-08-14 10:33:51,306: 	 Will use CRAB configuration file crab_config.py
DEBUG 2015-08-14 10:33:51,306: 	 Loading CRAB configuration file.
DEBUG 2015-08-14 10:33:51,327: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-14 10:33:51,328: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-08-14 10:33:51,328: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/test/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-08-17 16:12:08,586: 	 Executing command: 'submit'
DEBUG 2015-08-17 16:12:08,587: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-08-17 16:12:08,600: 	 Checking credentials
DEBUG 2015-08-17 16:12:08,601: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-08-17 16:12:08,601: 	 Getting proxy life time left
DEBUG 2015-08-17 16:12:09,214: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 71038

 error: 
 retcode : 0
DEBUG 2015-08-17 16:12:10,021: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 71038

 error: 
 retcode : 0
DEBUG 2015-08-17 16:12:10,021: 	 Proxy valid for 19:43:58 hours
INFO 2015-08-17 16:12:10,022: 	 Will use CRAB configuration file crab.py
DEBUG 2015-08-17 16:12:10,022: 	 Loading CRAB configuration file.
DEBUG 2015-08-17 16:12:10,023: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-17 16:12:10,024: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/data/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-08-17 16:12:10,024: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/data/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-08-19 12:16:15,315: 	 Executing command: 'submit'
DEBUG 2015-08-19 12:16:15,316: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-08-19 12:16:15,333: 	 Checking credentials
DEBUG 2015-08-19 12:16:15,334: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-08-19 12:16:15,334: 	 Getting proxy life time left
DEBUG 2015-08-19 12:16:15,941: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 84725

 error: 
 retcode : 0
DEBUG 2015-08-19 12:16:16,549: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 84724

 error: 
 retcode : 0
DEBUG 2015-08-19 12:16:16,549: 	 Proxy valid for 23:32:05 hours
INFO 2015-08-19 12:16:16,549: 	 Will use CRAB configuration file crab.py
DEBUG 2015-08-19 12:16:16,550: 	 Loading CRAB configuration file.
DEBUG 2015-08-19 12:16:16,557: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-19 12:16:16,557: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/data/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-08-19 12:16:16,557: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/data/crab_m2n' already exists 
Please change the requestName in the config file
DEBUG 2015-08-25 16:53:26,560: 	 Executing command: 'status'
DEBUG 2015-08-25 16:53:26,561: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
ERROR 2015-08-25 16:53:26,566: 	 Error: VBF/crab_m2n/ is not a valid CRAB project directory.
ERROR 2015-08-25 16:53:26,566: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 253, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/status.py", line 731, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 563, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: VBF/crab_m2n/ is not a valid CRAB project directory.
DEBUG 2015-08-27 09:50:54,165: 	 Executing command: 'submit'
DEBUG 2015-08-27 09:50:54,165: 	 Found CRAB cache file /afs/cern.ch/user/m/molszews/.crab3
DEBUG 2015-08-27 09:50:54,176: 	 Checking credentials
DEBUG 2015-08-27 09:50:54,177: 	 Found proxy file /tmp/x509up_u39587
DEBUG 2015-08-27 09:50:54,177: 	 Getting proxy life time left
DEBUG 2015-08-27 09:50:54,688: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -timeleft
 output : 84434

 error: 
 retcode : 0
DEBUG 2015-08-27 09:50:55,296: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u39587 -actimeleft
 output : 84432

 error: 
 retcode : 0
DEBUG 2015-08-27 09:50:55,296: 	 Proxy valid for 23:27:14 hours
INFO 2015-08-27 09:50:55,296: 	 Will use CRAB configuration file crab.py
DEBUG 2015-08-27 09:50:55,296: 	 Loading CRAB configuration file.
DEBUG 2015-08-27 09:50:55,522: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-08-27 09:50:55,522: 	 Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/vbf_synch_o1/crab_m2n' already exists 
Please change the requestName in the config file
ERROR 2015-08-27 09:50:55,522: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 133, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/bin/crab", line 119, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/molszews/CMSSW/tautau/M2N/CMSSW_7_4_5/src/m2n/maxi2ntuples/python/vbf_synch_o1/crab_m2n' already exists 
Please change the requestName in the config file
